const userType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  FETCH_GMAIL_AUTH_START: "FETCH_GMAIL_AUTH_START",
  FETCH_GMAIL_AUTH_SUCCESS: "FETCH_GMAIL_AUTH_SUCCESS",
  FETCH_GMAIL_AUTH_FAILURE: "FETCH_GMAIL_AUTH_FAILURE",
  FETCH_EMAIL_AUTH_START: "FETCH_EMAIL_AUTH_START",
  FETCH_EMAIL_AUTH_SUCCESS: "FETCH_EMAIL_AUTH_SUCCESS",
  FETCH_EMAIL_AUTH_FAILURE: "FETCH_EMAIL_AUTH_FAILURE",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE: "SIGNOUT_FAILURE",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export default userType;
